# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
encoding: utf-8
title: プログラミング演習A
email: enshu@ecei.tohoku.ac.jp
description: > # this means to ignore newlines until "baseurl:"
  東北大学 電気情報物理工学科 プログラミング演習A (第3セメスター)
baseurl: "/ppa" # the subpath of your site, e.g. /blog
url: "http://ecei-tohoku.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
#exclude: ['_tools']
#markdown: GFM # still unlcear if it works or not
